spring:
  application:
    name: problem-reproduce
  jms:
    servicebus:
      connection-string: "****"
      idle-timeout: 1800000
      pricing-tier: PREMIUM
      prefetch-policy:
        all: 1
  profiles:
    active: develop
