spring:
  application:
    name: problem-reproduce
    # FYI: I (rujche) use AzureCliCredential.
    # Use AzureCliCredential not required to run this sample, you can use other method instead.
    # For example: client-id and client-secret.
    # cloud:
    #   azure:
    #     credential:
    #       client-id:
    #       client-secret:
  jms:
    servicebus:
      # FYI: I (rujche) use AzureCliCredential.
      # Use AzureCliCredential not required to run this sample, you can use other method instead.
      # For example: connection-string.
      # connection-string:
      namespace:
      idle-timeout: 1800000
      passwordless-enabled: true # Set false if you use connection-string.
      pricing-tier: PREMIUM
      prefetch-policy:
        all: 1
  profiles:
    active: develop
